### ISSUE TITLE
Unit tests for Minimal Circles path

### ISSUE THREAD

**Issue by Gabrieldowen** [Gabrieldowen/NOTAMyWatch#19]
"let's vet that if we call getPath with two points "very close" to one another that we get back a two-element list and match the origin and destination with no points in between vs. calling getPath with two "further away from one another" points that require some intermediate steps."

**Comment by n-grounds** [comment]
I see there was a branch made for this unit test code, but it was never merged back to main.  Is that expected?  Shouldn't the ticket be closed/done only when its code changes are merged to main?

**Comment by Gabrieldowen** [comment]
Yes I should've done a pull request before closing my mistake. Once I get to my computer I'll create a pull request

**Comment by Gabrieldowen** [comment]
re-opened I made some oversight with one of the more important tests
