### ISSUE TITLE
Deciding on what variables we need to pass to API

### ISSUE THREAD

**Issue by Gabrieldowen** [Gabrieldowen/NOTAMyWatch#4]

**Comment by JmzCS50** [comment]
as of 2/10/2024 , we are using :

Response Format: geoJson
Effective Start Date: 2024-02-01T00:00:00Z (Beginning of the month)
Effective End Date: 2024-02-28T23:59:59Z (End of the month)
Longitude: -118.4085 (LAX Longitude)
Latitude: 33.9416 (LAX Latitude)
Radius: 100 (Assuming nautical miles, adjust if the unit is different)
Sort By Parameter: notamType
Sort Order: Asc
