### ISSUE TITLE
Figure out FAA API call limit

### ISSUE THREAD

**Issue by okie-creator** [Gabrieldowen/NOTAMyWatch#57]

**Comment by okie-creator** [comment]
FAA API can take 100 calls at a time

**Comment by n-grounds** [comment]
100 concurrent calls for a given clientId/clientSecret, is that what you are saying?

**Comment by okie-creator** [comment]
Yes Sir, that's what I found.  I found a section of the FAA API Help that described 100 free calls for the clientid/clientSecret. It's further supported that I have multithread API Calls branch running at 40 concurrent threads without encountering a bad api call error.
