### ISSUE TITLE
Come up with better repo name

### ISSUE THREAD

**Issue by Gabrieldowen** [Gabrieldowen/NOTAMyWatch#8]

**Comment by okie-creator** [comment]
CAPSTONE_SPRING_24_PROJECT
NOTAM_API_FLIGHT_PROJECT
DR_GROUND'S_SUPER_PROJECT

**Comment by DavidRamirezz** [comment]
CAPTSTONE_PROJECT

**Comment by Gabrieldowen** [comment]
some names I was thinking of:
NOTAMyWatch
NOTAM_Navigator
NicheNOTAM
NOTAMNeaten
NarrowNOTAM

I say we keep thinking about it and then vote on it next meeting

**Comment by okie-creator** [comment]
I like NOTAMyWatch
